/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Extract the number of X and Y components from a BlurHash string.
 *
 * @param blurhash - The BlurHash string.
 * @returns An object with componentsX and componentsY fields.
 */
export interface Components {
  componentsX: number
  componentsY: number
}

/**
 * Decode a BlurHash string into raw RGB pixel data.
 *
 * @param blurhash - The BlurHash string to decode.
 * @param width - Desired output width in pixels.
 * @param height - Desired output height in pixels.
 * @param punch - Contrast adjustment factor (default 1.0).
 * @returns A Buffer of length width * height * 3 containing RGB pixel data.
 */
export declare function decode(blurhash: string, width: number, height: number, punch?: number | undefined | null): Buffer

/**
 * Async version of decode that runs on the libuv thread pool.
 * Returns a Promise<Buffer>.
 *
 * @param blurhash - The BlurHash string to decode.
 * @param width - Desired output width in pixels.
 * @param height - Desired output height in pixels.
 * @param punch - Contrast adjustment factor (default 1.0).
 * @returns A Promise resolving to a Buffer of RGB pixel data.
 */
export declare function decodeAsync(blurhash: string, width: number, height: number, punch?: number | undefined | null): Promise<unknown>

/**
 * Decode a BlurHash string into a Uint8Array (for browser/Deno compatibility).
 *
 * @param blurhash - The BlurHash string to decode.
 * @param width - Desired output width in pixels.
 * @param height - Desired output height in pixels.
 * @param punch - Contrast adjustment factor (default 1.0).
 * @returns A Uint8Array of length width * height * 3 containing RGB pixel data.
 */
export declare function decodeToUint8Array(blurhash: string, width: number, height: number, punch?: number | undefined | null): Uint8Array

/**
 * Encode image pixel data into a BlurHash string.
 *
 * @param data - Raw pixel bytes in RGB order (length must be width * height * 3).
 * @param width - Image width in pixels.
 * @param height - Image height in pixels.
 * @param components_x - Number of horizontal components (1..=9, default 4).
 * @param components_y - Number of vertical components (1..=9, default 4).
 * @returns The BlurHash string.
 */
export declare function encode(data: Buffer, width: number, height: number, componentsX?: number | undefined | null, componentsY?: number | undefined | null): string

/**
 * Async version of encode that runs on the libuv thread pool.
 * Returns a Promise<string>.
 *
 * @param data - Raw pixel bytes in RGB order (length must be width * height * 3).
 * @param width - Image width in pixels.
 * @param height - Image height in pixels.
 * @param components_x - Number of horizontal components (1..=9, default 4).
 * @param components_y - Number of vertical components (1..=9, default 4).
 * @returns A Promise resolving to the BlurHash string.
 */
export declare function encodeAsync(data: Buffer, width: number, height: number, componentsX?: number | undefined | null, componentsY?: number | undefined | null): Promise<unknown>

/**
 * Encode from a Uint8Array (for browser/Deno compatibility).
 *
 * @param data - Raw pixel bytes as Uint8Array in RGB order.
 * @param width - Image width in pixels.
 * @param height - Image height in pixels.
 * @param components_x - Number of horizontal components (1..=9, default 4).
 * @param components_y - Number of vertical components (1..=9, default 4).
 * @returns The BlurHash string.
 */
export declare function encodeFromUint8Array(data: Uint8Array, width: number, height: number, componentsX?: number | undefined | null, componentsY?: number | undefined | null): string

export declare function getComponents(blurhash: string): Components

/** Convert a linear RGB value (0.0-1.0) to an sRGB byte value (0-255). */
export declare function linearToSrgb(value: number): number

/** Convert an sRGB byte value (0-255) to linear RGB (0.0-1.0). */
export declare function srgbToLinear(value: number): number
